name: Deploy Dist
on: [push,workflow_dispatch]
jobs:
    test: 
        runs-on: ubuntu-latest
        steps: 
            - name: Get Code
              uses: actions/checkout@v5
            #   run: |
            #     echo "cloning repo.."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git
            - name: Install node JS 20
              uses: actions/setup-node@v5
              with: 
                node-version: 20
            # - name: Print the Node Version
            #   run: node -v
            - name: Install Dependencies
              run: npm ci #ci = Clearn Install
            - name: Run Tests
              run: npm run test
    deploy: 
        runs-on: ubuntu-latest
        steps: 
            - name: Get Code
              uses: actions/checkout@v5
            - name: Install node JS 20
              uses: actions/setup-node@v5
              with: 
                node-version: 20
            - name: Print the Node Version
              run: node -v
            - name: Install Dependencies
              run: npm ci #ci = Clearn Install
            - name: Build Project
              run: npm run build    
            - name: Deploy
              run: echo "Deploy Successfully"